name: Tsubakuro-Examples-CI

on: [push, pull_request, workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    timeout-minutes: 30
    defaults:
      run:
        shell: bash

    steps:
      - name: Setup_Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Assemble
        run: |
          ./gradlew -i clean assemble

      - name: Check
        run: |
          ./gradlew -i check --continue

      - name: Verify
        uses: project-tsurugi/tsurugi-annotations-action@v1
        if: always()
        with:
          junit_input: '**/build/test-results/**/TEST-*.xml'
          junit_test_src_dir: 'src/test/java'
          spotbugs_input: '**/build/reports/spotbugs/main/*.xml'
          checkstyle_input: '**/build/reports/checkstyle/main.xml'
